SET SESSION FOREIGN_KEY_CHECKS=0;

/* Drop Tables */

DROP TABLE IF EXISTS DETAIL_MENU;
DROP TABLE IF EXISTS GRANT_AUTH;
DROP TABLE IF EXISTS LOWER_MENU;
DROP TABLE IF EXISTS UPPER_MENU;
DROP TABLE IF EXISTS AUTH;
DROP TABLE IF EXISTS BOARD_CMT;
DROP TABLE IF EXISTS BOARD;
DROP TABLE IF EXISTS COMMON_CD;
DROP TABLE IF EXISTS LEDGER_RCD;
DROP TABLE IF EXISTS MEANS;
DROP TABLE IF EXISTS PURPOSE_DTL;
DROP TABLE IF EXISTS PURPOSE;
DROP TABLE IF EXISTS SOURCE_BRD;
DROP TABLE IF EXISTS WHITE_USER;




/* Create Tables */

CREATE TABLE AUTH
(
	AUTH_SEQ int NOT NULL AUTO_INCREMENT,
	AUTH_NM varchar(20) NOT NULL,
	AUTH_ODR int NOT NULL,
	AUTH_CMT varchar(50) NOT NULL,
	PRIMARY KEY (AUTH_SEQ),
	UNIQUE (AUTH_SEQ),
	UNIQUE (AUTH_NM)
);


CREATE TABLE BOARD
(
	BOARD_SEQ int NOT NULL AUTO_INCREMENT,
	USER_SEQ int NOT NULL,
	BOARD_TP_CD varchar(6) NOT NULL,
	TITLE varchar(50) NOT NULL,
	CONTENT varchar(4000) NOT NULL,
	EDIT_DATE datetime NOT NULL,
	REG_DATE datetime NOT NULL,
	PRIMARY KEY (BOARD_SEQ),
	UNIQUE (BOARD_SEQ)
);


CREATE TABLE BOARD_CMT
(
	BOARD_CMT_SEQ int NOT NULL AUTO_INCREMENT,
	BOARD_SEQ int NOT NULL,
	USER_SEQ int NOT NULL,
	COMMENT varchar(1000) NOT NULL,
	EDIT_DATE datetime NOT NULL,
	REG_DATE datetime NOT NULL,
	PRIMARY KEY (BOARD_CMT_SEQ),
	UNIQUE (BOARD_CMT_SEQ)
);


CREATE TABLE COMMON_CD
(
	CODE_SEQ int NOT NULL AUTO_INCREMENT,
	CODE varchar(6) NOT NULL,
	CODE_PRT varchar(6) NOT NULL,
	CODE_NM varchar(20) NOT NULL,
	MOD_USER varchar(20) NOT NULL,
	MOD_DATE datetime NOT NULL,
	REG_USER varchar(20) NOT NULL,
	REG_DATE datetime NOT NULL,
	PRIMARY KEY (CODE_SEQ),
	UNIQUE (CODE)
);


CREATE TABLE DETAIL_MENU
(
	DETAIL_SEQ int NOT NULL AUTO_INCREMENT,
	LOWER_SEQ int NOT NULL,
	DETAIL_NM varchar(20) NOT NULL,
	DETAIL_URL varchar(20) NOT NULL,
	DETAIL_ODR int NOT NULL,
	AUTH_SEQ int NOT NULL,
	SHOW_YN varchar(1) NOT NULL,
	PRIMARY KEY (DETAIL_SEQ),
	UNIQUE (DETAIL_SEQ),
	UNIQUE (AUTH_SEQ)
);


CREATE TABLE GRANT_AUTH
(
	GRANT_AUTH_SEQ int NOT NULL AUTO_INCREMENT,
	USER_SEQ int NOT NULL,
	AUTH_SEQ int NOT NULL,
	PRIMARY KEY (GRANT_AUTH_SEQ),
	UNIQUE (GRANT_AUTH_SEQ)
);


CREATE TABLE LEDGER_RCD
(
	LEDGER_RCD_SEQ int NOT NULL AUTO_INCREMENT,
	USER_SEQ int NOT NULL,
	RECORD_DATE datetime NOT NULL,
	POSITION varchar(20),
	CONTENT varchar(50),
	PURPOSE_SEQ int NOT NULL,
	PURPOSE_DTL_SEQ int NOT NULL,
	MEANS_SEQ int NOT NULL,
	MONEY int NOT NULL,
	STATS_YN varchar(1) DEFAULT 'Y' NOT NULL,
	EDIT_DATE datetime NOT NULL,
	REG_DATE datetime NOT NULL,
	PRIMARY KEY (LEDGER_RCD_SEQ),
	UNIQUE (LEDGER_RCD_SEQ)
);


CREATE TABLE LOWER_MENU
(
	LOWER_SEQ int NOT NULL AUTO_INCREMENT,
	UPPER_SEQ int NOT NULL,
	LOWER_NM varchar(20) NOT NULL,
	LOWER_URL varchar(40) NOT NULL,
	LOWER_ODR int NOT NULL,
	AUTH_SEQ int NOT NULL,
	SHOW_YN varchar(1) NOT NULL,
	PRIMARY KEY (LOWER_SEQ),
	UNIQUE (LOWER_SEQ)
);


CREATE TABLE MEANS
(
	MEANS_SEQ int NOT NULL,
	USER_SEQ int NOT NULL,
	MEANS_NM varchar(50) NOT NULL,
	MEANS_DTL_NM varchar(50),
	MEANS_INFO varchar(50),
	MEANS_USE_YN varchar(1) NOT NULL,
	MEANS_RMK varchar(100),
	MEANS_ODR int NOT NULL,
	PRIMARY KEY (MEANS_SEQ)
);


CREATE TABLE PURPOSE
(
	PURPOSE_SEQ int NOT NULL AUTO_INCREMENT,
	USER_SEQ int NOT NULL,
	PURPOSE_NM varchar(20) NOT NULL,
	PURPOSE_TP_CD varchar(6) NOT NULL,
	PURPOSE_ODR int NOT NULL,
	PRIMARY KEY (PURPOSE_SEQ),
	UNIQUE (PURPOSE_SEQ)
);


CREATE TABLE PURPOSE_DTL
(
	PURPOSE_DTL_SEQ int NOT NULL AUTO_INCREMENT,
	PURPOSE_SEQ int NOT NULL,
	USER_SEQ int NOT NULL,
	PURPOSE_DTL_NM varchar(20) NOT NULL,
	PURPOSE_DTL_ODR int NOT NULL,
	PRIMARY KEY (PURPOSE_DTL_SEQ),
	UNIQUE (PURPOSE_DTL_SEQ)
);


CREATE TABLE SOURCE_BRD
(
	SOURCE_SEQ int NOT NULL AUTO_INCREMENT,
	USER_SEQ int NOT NULL,
	SOURCE_LANG_CD varchar(6) NOT NULL,
	TITLE varchar(50) NOT NULL,
	CONTENT varchar(4000) NOT NULL,
	EDIT_DATE datetime NOT NULL,
	REG_DATE datetime NOT NULL,
	PRIMARY KEY (SOURCE_SEQ),
	UNIQUE (SOURCE_SEQ)
);


CREATE TABLE UPPER_MENU
(
	UPPER_SEQ int NOT NULL AUTO_INCREMENT,
	UPPER_NM varchar(20) NOT NULL,
	UPPER_URL varchar(40) NOT NULL,
	UPPER_ODR int NOT NULL,
	AUTH_SEQ int NOT NULL,
	SHOW_YN varchar(1) NOT NULL,
	PRIMARY KEY (UPPER_SEQ),
	UNIQUE (UPPER_SEQ)
);


CREATE TABLE WHITE_USER
(
	USER_SEQ int NOT NULL AUTO_INCREMENT,
	USER_ID varchar(20) NOT NULL,
	USER_NM varchar(10) NOT NULL,
	USER_PASS varchar(60) NOT NULL,
	USE_YN varchar(1) DEFAULT 'Y' NOT NULL,
	PRIMARY KEY (USER_SEQ),
	UNIQUE (USER_SEQ),
	UNIQUE (USER_ID)
);



/* Create Foreign Keys */

ALTER TABLE DETAIL_MENU
	ADD FOREIGN KEY (AUTH_SEQ)
	REFERENCES AUTH (AUTH_SEQ)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE GRANT_AUTH
	ADD FOREIGN KEY (AUTH_SEQ)
	REFERENCES AUTH (AUTH_SEQ)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE LOWER_MENU
	ADD FOREIGN KEY (AUTH_SEQ)
	REFERENCES AUTH (AUTH_SEQ)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE UPPER_MENU
	ADD FOREIGN KEY (AUTH_SEQ)
	REFERENCES AUTH (AUTH_SEQ)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE BOARD_CMT
	ADD FOREIGN KEY (BOARD_SEQ)
	REFERENCES BOARD (BOARD_SEQ)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE DETAIL_MENU
	ADD FOREIGN KEY (LOWER_SEQ)
	REFERENCES LOWER_MENU (LOWER_SEQ)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE LEDGER_RCD
	ADD FOREIGN KEY (MEANS_SEQ)
	REFERENCES MEANS (MEANS_SEQ)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE LEDGER_RCD
	ADD FOREIGN KEY (PURPOSE_SEQ)
	REFERENCES PURPOSE (PURPOSE_SEQ)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE PURPOSE_DTL
	ADD FOREIGN KEY (PURPOSE_SEQ)
	REFERENCES PURPOSE (PURPOSE_SEQ)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE LEDGER_RCD
	ADD FOREIGN KEY (PURPOSE_DTL_SEQ)
	REFERENCES PURPOSE_DTL (PURPOSE_DTL_SEQ)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE LOWER_MENU
	ADD FOREIGN KEY (UPPER_SEQ)
	REFERENCES UPPER_MENU (UPPER_SEQ)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE BOARD
	ADD FOREIGN KEY (USER_SEQ)
	REFERENCES WHITE_USER (USER_SEQ)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE BOARD_CMT
	ADD FOREIGN KEY (USER_SEQ)
	REFERENCES WHITE_USER (USER_SEQ)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE GRANT_AUTH
	ADD FOREIGN KEY (USER_SEQ)
	REFERENCES WHITE_USER (USER_SEQ)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE LEDGER_RCD
	ADD FOREIGN KEY (USER_SEQ)
	REFERENCES WHITE_USER (USER_SEQ)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE MEANS
	ADD FOREIGN KEY (USER_SEQ)
	REFERENCES WHITE_USER (USER_SEQ)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE PURPOSE
	ADD FOREIGN KEY (USER_SEQ)
	REFERENCES WHITE_USER (USER_SEQ)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE PURPOSE_DTL
	ADD FOREIGN KEY (USER_SEQ)
	REFERENCES WHITE_USER (USER_SEQ)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE SOURCE_BRD
	ADD FOREIGN KEY (USER_SEQ)
	REFERENCES WHITE_USER (USER_SEQ)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;



