/* 권한 insert  */
INSERT INTO AUTHORITY VALUES('9999', 'developer');
INSERT INTO AUTHORITY VALUES('9998', 'administrator');
INSERT INTO AUTHORITY VALUES('1000', 'user');

/* 사용자 insert */
INSERT INTO WHITE_USER(AUTHORITY_NO, USER_ID, USER_NAME, USER_PASSWD)
VALUES('9999', 'leedev', '이제훈', '$2a$06$dB98wU7W4fCUpw8YDXFyIeyOwOEO2Lc62HLqSH3QWkE3TWhHQl40a');

INSERT INTO WHITE_USER(AUTHORITY_NO, USER_ID, USER_NAME, USER_PASSWD)
VALUES('1000', 'jhkotoba', '이제훈', '$2a$06$dB98wU7W4fCUpw8YDXFyIeyOwOEO2Lc62HLqSH3QWkE3TWhHQl40a');


/* 사용자 은행 insert leedev TEST data*/
INSERT 
INTO USER_BANK(USER_SEQ, BANK_NAME, BANK_ACCOUNT, BANK_NOW_USE_YN)
VALUES(
	(SELECT USER_SEQ FROM WHITE_USER WHERE USER_ID = 'leedev'),		-- 사용자 
    '국민은행',														-- 은행명
    '172601-04-067855',												-- 계좌번호    
    'Y'																-- 사용여부
    );  
INSERT 
INTO USER_BANK(USER_SEQ, BANK_NAME, BANK_ACCOUNT, BANK_NOW_USE_YN)
VALUES(
	(SELECT USER_SEQ FROM WHITE_USER WHERE USER_ID = 'leedev'),
    '우리은행',
    '1002-340-227683',  
    'Y'
    );
    
 /* 목적 */
 /* 1 */
 INSERT INTO PURPOSE(USER_SEQ, PUR_ORDER, PURPOSE)
 VALUES(1, 1, '초기금액');
  /* 2 */
 INSERT INTO PURPOSE(USER_SEQ, PUR_ORDER, PURPOSE)
 VALUES(1, 2,'식비');
  /* 3 */
 INSERT INTO PURPOSE(USER_SEQ, PUR_ORDER, PURPOSE)
 VALUES(1, 3, '통신비');
  /* 4 */
 INSERT INTO PURPOSE(USER_SEQ, PUR_ORDER, PURPOSE)
 VALUES(1, 4, '교통비');
  /* 5 */
 INSERT INTO PURPOSE(USER_SEQ, PUR_ORDER, PURPOSE)
 VALUES(1, 5, '입금');
  /* 6 */
 INSERT INTO PURPOSE(USER_SEQ, PUR_ORDER, PURPOSE)
 VALUES(1, 6, '출금');
 /* 7 */
 INSERT INTO PURPOSE(USER_SEQ, PUR_ORDER, PURPOSE)
 VALUES(1, 7, '급여');
 
    

/* 사용자 금전 기록 */
/*
INSERT
INTO MONEY_RECORD(USER_SEQ, RECORD_TIME, CONTENT, PURPOSE_SEQ, USER_BANK_SEQ, BANK_NAME, BANK_ACCOUNT, BANK_RECORD_USE_YN, IN_EXP_MONEY, READY_MONEY, RESULT_BANK_MONEY)
VALUES(
	(SELECT USER_SEQ FROM WHITE_USER WHERE USER_ID = 'leedev'),
    '2017-04-20 00:00:00',
    '초기금액',
    1,
    '현금',
    'readyMoney',
    'X',
    50000,
    50000,
    0
);

INSERT
INTO MONEY_RECORD(USER_SEQ, RECORD_TIME, CONTENT, PURPOSE_SEQ, USER_BANK_SEQ, BANK_NAME, BANK_ACCOUNT, BANK_RECORD_USE_YN, IN_EXP_MONEY, READY_MONEY, RESULT_BANK_MONEY)
VALUES(
	(SELECT USER_SEQ FROM WHITE_USER WHERE USER_ID = 'leedev'),
    '2017-04-21 00:00:00',
    '점심',
    2,
    '현금',
    'readyMoney',
    'X',
    -5000,
    45000,
    0,
    now()
    
);

INSERT
INTO MONEY_RECORD(USER_SEQ, RECORD_TIME, CONTENT, PURPOSE_SEQ, USER_BANK_SEQ, BANK_NAME, BANK_ACCOUNT, BANK_RECORD_USE_YN, IN_EXP_MONEY, READY_MONEY, RESULT_BANK_MONEY)
VALUES(
	(SELECT USER_SEQ FROM WHITE_USER WHERE USER_ID = 'leedev'),
    '2017-04-22 00:00:00',
    '교통카드 충전',
    4,
    null,
    '현금',
    'readyMoney',
    'X',
    -10000,
    35000,
    0,
    now()
);

INSERT
INTO MONEY_RECORD(USER_SEQ, RECORD_TIME, CONTENT, PURPOSE_SEQ, USER_BANK_SEQ, BANK_NAME, BANK_ACCOUNT, BANK_RECORD_USE_YN, IN_EXP_MONEY, READY_MONEY, RESULT_BANK_MONEY)
VALUES(
	(SELECT USER_SEQ FROM WHITE_USER WHERE USER_ID = 'leedev'),
    '2017-04-23 00:00:00',
    '국민카드 입금',
    5,
    1,
    '국민은행',
    '172601-04-067855',
    'Y',
    50000,
    0,
    50000
);

INSERT
INTO MONEY_RECORD(USER_SEQ, RECORD_TIME, CONTENT, PURPOSE_SEQ, USER_BANK_SEQ, BANK_NAME, BANK_ACCOUNT, BANK_RECORD_USE_YN, IN_EXP_MONEY, READY_MONEY, RESULT_BANK_MONEY)
VALUES(
	(SELECT USER_SEQ FROM WHITE_USER WHERE USER_ID = 'leedev'),
    '2017-04-24 00:00:00',
    '핸드폰 약정',
    3,
    1,
    '국민은행',
    '172601-04-067855',
    'Y',
    -10000,
    0,
    40000
);

INSERT
INTO MONEY_RECORD(USER_SEQ, RECORD_TIME, CONTENT, PURPOSE_SEQ, USER_BANK_SEQ, BANK_NAME, BANK_ACCOUNT, BANK_RECORD_USE_YN, IN_EXP_MONEY, READY_MONEY, RESULT_BANK_MONEY)
VALUES(
	(SELECT USER_SEQ FROM WHITE_USER WHERE USER_ID = 'leedev'),
    '2017-04-25 00:00:00',
    '급여',
    7,
    null,
    '현금',
    'readyMoney',
	'X',
    -10000,
    25000,
    0
);

INSERT
INTO MONEY_RECORD(USER_SEQ, RECORD_TIME, CONTENT, PURPOSE_SEQ, USER_BANK_SEQ, BANK_NAME, BANK_ACCOUNT, BANK_RECORD_USE_YN, IN_EXP_MONEY, READY_MONEY, RESULT_BANK_MONEY)
VALUES(
	(SELECT USER_SEQ FROM WHITE_USER WHERE USER_ID = 'leedev'),
    '2017-04-27 00:00:00',
    '우리은행 입금',
    5,
    2,
    '우리은행',
    '1002-340-227683',
    'Y',
    50000,
    0,
    50000
);*/
